<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <properties>
        <bundle.symbolicName>org.cytoscape.nedrex.NeDRex</bundle.symbolicName>
        <bundle.namespace>org.cytoscape.nedrex</bundle.namespace>
        <cytoscape-dependency-version>3.6.1</cytoscape-dependency-version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modelVersion>4.0.0</modelVersion>
    <groupId>org.cytoscape.nedrex</groupId>
    <artifactId>NeDRex</artifactId>
    <version>2.1.0-rc2</version>
    <name>NeDRex</name>
    <packaging>bundle</packaging>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <!-- Cytoscape requires Java 1.8 -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <executions>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <optimize>true</optimize>
                    <showWarnings>true</showWarnings>
                    <showDeprecation>true</showDeprecation>
                    <compilerArguments>
                        <Xmaxwarns>10000</Xmaxwarns>
                        <Xmaxerrs>10000</Xmaxerrs>
                    </compilerArguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.7.1</version>
                <configuration>
                    <redirectTestOutputToFile>true</redirectTestOutputToFile>
                </configuration>
            </plugin>
            <!-- Generates the OSGi metadata based on the osgi.bnd file. -->
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>3.2.0</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <_dsannotations>*</_dsannotations>
                        <Bundle-SymbolicName>${bundle.symbolicName}</Bundle-SymbolicName>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Export-Package>${bundle.namespace}</Export-Package>
                        <Private-Package>${bundle.namespace}.internal.*</Private-Package>
                        <Bundle-Activator>${bundle.namespace}.internal.CyActivator</Bundle-Activator>
                        <Embed-Dependency>*;scope=compile|runtime;groupId=!org.cytoscape|org.osgi</Embed-Dependency>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <!-- Links to the Cytoscape Maven repositories. -->
    <repositories>
        <repository>
            <id>cytoscape_snapshots</id>
            <snapshots>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
            <name>Cytoscape Snapshots</name>
            <url>https://nrnb-nexus.ucsd.edu/repository/cytoscape_snapshots/</url>
        </repository>
        <repository>
            <id>cytoscape_releases</id>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
            </releases>
            <name>Cytoscape Releases</name>
            <url>https://nrnb-nexus.ucsd.edu/repository/cytoscape_releases/</url>
        </repository>
        <!-- Added following 2 repositories to test. -->
        <repository>
            <id>apache-repo-releases</id>
            <url>https://repository.apache.org/content/repositories/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>apache_maven2</id>
            <url>https://repo.maven.apache.org/maven2/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>

    <!-- Dependencies needed to compile this project. -->
    <dependencies>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.scr</artifactId>
            <version>1.8.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.shell</artifactId>
            <version>1.4.3</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.core</artifactId>
            <version>6.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>osgi.cmpn</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>service-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>swing-application-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>session-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>core-task-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>command-executor-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>work-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>webservice-swing-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>
        <dependency>
            <groupId>org.cytoscape</groupId>
            <artifactId>layout-api</artifactId>
            <version>${cytoscape-dependency-version}</version>
        </dependency>

        <!-- Logging -->
        <dependency>
            <groupId>org.ops4j.pax.logging</groupId>
            <artifactId>pax-logging-api</artifactId>
            <version>1.5.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.logging</groupId>
            <artifactId>pax-logging-service</artifactId>
            <version>1.11.17</version>
            <scope>provided</scope>

        </dependency>
        <!-- jgrapht -->
        <dependency>
            <groupId>org.jgrapht</groupId>
            <artifactId>jgrapht-core</artifactId>
            <version>1.3.0</version>
            <type>jar</type>
            <optional>true</optional>
        </dependency>
        <!-- json -->
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <!-- httpComponent -->
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.13</version>
            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <groupId>commons-codec</groupId>
                    <artifactId>commons-codec</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.16</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.2.3</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.16.0</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.7</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>3.6.1</version>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
